export const COUNTRIES = [
    { code: 'GE', name: 'საქართველო (Georgia)', phoneCode: '+995' },
    { code: 'US', name: 'აშშ (USA)', phoneCode: '+1' },
    { code: 'UA', name: 'უკრაინა (Ukraine)', phoneCode: '+380' },
    { code: 'RU', name: 'რუსეთი (Russia)', phoneCode: '+7' },
    { code: 'TR', name: 'თურქეთი (Turkey)', phoneCode: '+90' },
    { code: 'AZ', name: 'აზერბაიჯანი (Azerbaijan)', phoneCode: '+994' },
    { code: 'AM', name: 'სომხეთი (Armenia)', phoneCode: '+374' },
    { code: 'DE', name: 'გერმანია (Germany)', phoneCode: '+49' },
    { code: 'FR', name: 'საფრანგეთი (France)', phoneCode: '+33' },
    { code: 'GB', name: 'დიდი ბრიტანეთი (UK)', phoneCode: '+44' },
    { code: 'IT', name: 'იტალია (Italy)', phoneCode: '+39' },
    { code: 'ES', name: 'ესპანეთი (Spain)', phoneCode: '+34' },
    { code: 'GR', name: 'საბერძნეთი (Greece)', phoneCode: '+30' },
    { code: 'PL', name: 'პოლონეთი (Poland)', phoneCode: '+48' },
    { code: 'IL', name: 'ისრაელი (Israel)', phoneCode: '+972' },
    { code: 'CN', name: 'ჩინეთი (China)', phoneCode: '+86' },
    { code: 'JP', name: 'იაპონია (Japan)', phoneCode: '+81' },
    { code: 'KZ', name: 'ყაზახეთი (Kazakhstan)', phoneCode: '+7' },
    { code: 'BY', name: 'ბელარუსი (Belarus)', phoneCode: '+375' },
    { code: 'IR', name: 'ირანი (Iran)', phoneCode: '+98' },
    { code: 'IQ', name: 'ერაყი (Iraq)', phoneCode: '+964' },
    { code: 'IN', name: 'ინდოეთი (India)', phoneCode: '+91' },
    { code: 'CA', name: 'კანადა (Canada)', phoneCode: '+1' },
    { code: 'AU', name: 'ავსტრალია (Australia)', phoneCode: '+61' },
    { code: 'AT', name: 'ავსტრია (Austria)', phoneCode: '+43' },
    { code: 'BE', name: 'ბელგია (Belgium)', phoneCode: '+32' },
    { code: 'BG', name: 'ბულგარეთი (Bulgaria)', phoneCode: '+359' },
    { code: 'BR', name: 'ბრაზილია (Brazil)', phoneCode: '+55' },
    { code: 'CZ', name: 'ჩეხეთი (Czech Republic)', phoneCode: '+420' },
    { code: 'DK', name: 'დანია (Denmark)', phoneCode: '+45' },
    { code: 'EG', name: 'ეგვიპტე (Egypt)', phoneCode: '+20' },
    { code: 'EE', name: 'ესტონეთი (Estonia)', phoneCode: '+372' },
    { code: 'FI', name: 'ფინეთი (Finland)', phoneCode: '+358' },
    { code: 'HU', name: 'უნგრეთი (Hungary)', phoneCode: '+36' },
    { code: 'IE', name: 'ირლანდია (Ireland)', phoneCode: '+353' },
    { code: 'LV', name: 'ლატვია (Latvia)', phoneCode: '+371' },
    { code: 'LT', name: 'ლიეტუვა (Lithuania)', phoneCode: '+370' },
    { code: 'MD', name: 'მოლდოვა (Moldova)', phoneCode: '+373' },
    { code: 'NL', name: 'ნიდერლანდები (Netherlands)', phoneCode: '+31' },
    { code: 'NO', name: 'ნორვეგია (Norway)', phoneCode: '+47' },
    { code: 'PT', name: 'პორტუგალია (Portugal)', phoneCode: '+351' },
    { code: 'RO', name: 'რუმინეთი (Romania)', phoneCode: '+40' },
    { code: 'SE', name: 'შვედეთი (Sweden)', phoneCode: '+46' },
    { code: 'CH', name: 'შვეიცარია (Switzerland)', phoneCode: '+41' },
    { code: 'AE', name: 'არაბთა გაერთიანებული საამიროები (UAE)', phoneCode: '+971' },
    { code: 'UZ', name: 'უზბეკეთი (Uzbekistan)', phoneCode: '+998' }
];
