export const COUNTRIES = [
    { code: 'GE', name: 'საქართველო (Georgia)' },
    { code: 'US', name: 'აშშ (USA)' },
    { code: 'UA', name: 'უკრაინა (Ukraine)' },
    { code: 'RU', name: 'რუსეთი (Russia)' },
    { code: 'TR', name: 'თურქეთი (Turkey)' },
    { code: 'AZ', name: 'აზერბაიჯანი (Azerbaijan)' },
    { code: 'AM', name: 'სომხეთი (Armenia)' },
    { code: 'DE', name: 'გერმანია (Germany)' },
    { code: 'FR', name: 'საფრანგეთი (France)' },
    { code: 'GB', name: 'დიდი ბრიტანეთი (UK)' },
    { code: 'IT', name: 'იტალია (Italy)' },
    { code: 'ES', name: 'ესპანეთი (Spain)' },
    { code: 'GR', name: 'საბერძნეთი (Greece)' },
    { code: 'PL', name: 'პოლონეთი (Poland)' },
    { code: 'IL', name: 'ისრაელი (Israel)' },
    { code: 'CN', name: 'ჩინეთი (China)' },
    { code: 'JP', name: 'იაპონია (Japan)' },
    { code: 'KZ', name: 'ყაზახეთი (Kazakhstan)' },
    { code: 'BY', name: 'ბელარუსი (Belarus)' },
    { code: 'IR', name: 'ირანი (Iran)' },
    { code: 'IQ', name: 'ერაყი (Iraq)' },
    { code: 'IN', name: 'ინდოეთი (India)' },
    { code: 'CA', name: 'კანადა (Canada)' },
    { code: 'AU', name: 'ავსტრალია (Australia)' },
    { code: 'AT', name: 'ავსტრია (Austria)' },
    { code: 'BE', name: 'ბელგია (Belgium)' },
    { code: 'BG', name: 'ბულგარეთი (Bulgaria)' },
    { code: 'BR', name: 'ბრაზილია (Brazil)' },
    { code: 'CZ', name: 'ჩეხეთი (Czech Republic)' },
    { code: 'DK', name: 'დანია (Denmark)' },
    { code: 'EG', name: 'ეგვიპტე (Egypt)' },
    { code: 'EE', name: 'ესტონეთი (Estonia)' },
    { code: 'FI', name: 'ფინეთი (Finland)' },
    { code: 'HU', name: 'უნგრეთი (Hungary)' },
    { code: 'IE', name: 'ირლანდია (Ireland)' },
    { code: 'LV', name: 'ლატვია (Latvia)' },
    { code: 'LT', name: 'ლიეტუვა (Lithuania)' },
    { code: 'MD', name: 'მოლდოვა (Moldova)' },
    { code: 'NL', name: 'ნიდერლანდები (Netherlands)' },
    { code: 'NO', name: 'ნორვეგია (Norway)' },
    { code: 'PT', name: 'პორტუგალია (Portugal)' },
    { code: 'RO', name: 'რუმინეთი (Romania)' },
    { code: 'SE', name: 'შვედეთი (Sweden)' },
    { code: 'CH', name: 'შვეიცარია (Switzerland)' },
    { code: 'AE', name: 'არაბთა გაერთიანებული საამიროები (UAE)' },
    { code: 'UZ', name: 'უზბეკეთი (Uzbekistan)' }
];
